package tugas_crud;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class frmMain extends javax.swing.JFrame {
    

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel18 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNIS = new javax.swing.JTextField();
        txtnname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbMan = new javax.swing.JRadioButton();
        rbWoman = new javax.swing.JRadioButton();
        txtClass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtpn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPD = new javax.swing.JScrollPane();
        txtPD = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtFL = new javax.swing.JTextField();
        txtcname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel18.setFont(new java.awt.Font("KG Blank Space Solid", 0, 24)); // NOI18N
        jLabel18.setText("FORM BIOADATA SISWA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel13.setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(410, 300, 40, 40);

        jPanel5.setBackground(new java.awt.Color(255, 0, 51));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel19);
        jLabel19.setBounds(450, 80, 270, 380);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Meltix Bold Demo", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("FORM PSG OF MOKLET STUDENT");
        jLabel16.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel16ComponentMoved(evt);
            }
        });
        jPanel5.add(jLabel16);
        jLabel16.setBounds(500, 30, 810, 80);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(-190, -30, 1600, 110);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 30, 40, 40);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 80, 270, 380);

        jLabel3.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 50, 30);

        txtNIS.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNISActionPerformed(evt);
            }
        });
        jPanel1.add(txtNIS);
        txtNIS.setBounds(120, 20, 210, 30);

        txtnname.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtnname);
        txtnname.setBounds(120, 100, 210, 30);

        jLabel4.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nick Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 110, 19);

        jLabel5.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 140, 19);

        rbMan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbMan);
        rbMan.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        rbMan.setText("Man");
        rbMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbManActionPerformed(evt);
            }
        });
        jPanel1.add(rbMan);
        rbMan.setBounds(120, 150, 140, 30);

        rbWoman.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbWoman);
        rbWoman.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        rbWoman.setText("Woman");
        rbWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWomanActionPerformed(evt);
            }
        });
        jPanel1.add(rbWoman);
        rbWoman.setBounds(120, 180, 140, 27);

        txtClass.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassActionPerformed(evt);
            }
        });
        jPanel1.add(txtClass);
        txtClass.setBounds(120, 220, 210, 30);

        jLabel6.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fav Lesson");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 410, 90, 19);

        jLabel12.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Class");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 220, 100, 19);

        txtpn.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpnActionPerformed(evt);
            }
        });
        jPanel1.add(txtpn);
        txtpn.setBounds(120, 360, 210, 30);

        jLabel15.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone Number");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 370, 120, 19);

        txtPD.setColumns(20);
        txtPD.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtPD.setRows(5);
        jPD.setViewportView(txtPD);

        jPanel1.add(jPD);
        jPD.setBounds(10, 510, 320, 90);

        jLabel2.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 260, 100, 19);

        txtFL.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtFL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFLActionPerformed(evt);
            }
        });
        jPanel1.add(txtFL);
        txtFL.setBounds(120, 400, 210, 30);

        txtcname.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtcname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtcname);
        txtcname.setBounds(120, 60, 210, 30);

        jLabel11.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Complete Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 60, 110, 19);

        jLabel7.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PSG Destination");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 490, 130, 19);

        txtFT.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFTActionPerformed(evt);
            }
        });
        jPanel1.add(txtFT);
        txtFT.setBounds(120, 440, 210, 30);

        jLabel14.setFont(new java.awt.Font("KG Blank Space Solid", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fav Teacher");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 450, 90, 19);

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane3.setViewportView(txtAddress);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(120, 260, 210, 90);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(20, 20, 340, 630);

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(510, 30, 40, 40);

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Complete Name", "Nick Name", "Gender", "Class", "Address", "Phone Number", "Fav Lesson", "Fav Teacher", "PSG des"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 20, 900, 170);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(370, 130, 930, 210);

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));
        jPanel3.setLayout(null);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(30, 30, 110, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(180, 30, 110, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton5.setText("EDIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(340, 30, 110, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(490, 30, 110, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(640, 30, 120, 40);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton6.setText("QUIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(810, 30, 110, 40);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(370, 20, 930, 100);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 80, 1410, 740);

        setSize(new java.awt.Dimension(1333, 822));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void selectData(){
        String kolom[] = {"NIS","Complete Name","Nick Name","Gender","Class","Address","Phone Number","Fav Lesson","PSG Destination"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_content";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                
                
                String NIS = rs.getString(1);
                String CompleteName = rs.getString(2);
                String NickName = rs.getString(3);
                String Gender = "";
                if ("Man".equals(rs.getString(4))) {
                    Gender = "Man";
                } else {
                    Gender = "Woman";
                }
                String Class = rs.getString(5);
                String Address = rs.getString(6);
                String PhoneNumber = rs.getString(7);
                String FavoriteLesson = rs.getString(8);
                String FavoriteTeacher = rs.getString(9);
                String PSGDestination = rs.getString(10);
                String data[] = {NIS,CompleteName,NickName,Gender,Class,Address,PhoneNumber,FavoriteLesson,FavoriteTeacher,PSGDestination};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
     
    private void jLabel16ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel16ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16ComponentMoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int baris = jTable1.getSelectedRow();
        if(baris != -1) {
            String NIS = jTable1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_content WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil dihapus", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal dihapus", "Gagal", jOptionPane1.WARNING_MESSAGE);
            }
        } else {
            jOptionPane1.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", jOptionPane1.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if ("".equals(txtNIS.getText()) || "".equals(txtcname.getText()) || "".equals(txtnname.getText()) || "".equals(txtClass.getText()) || "".equals(txtPD.getText()) ||  "".equals(txtpn.getText ()) ||  "".equals(txtFT.getText()) || "".equals(txtFL.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else {
            String Gender = "";
            if (rbMan.isSelected()) {
                Gender = "Man";
            } else {
                Gender = "Woman";
            }

            String SQL = "UPDATE tb_content SET "
            + "Complete_Name='"+ txtcname.getText()+"', "
            + "Nick_Name='"+ txtnname.getText()+"', "
            + "Gender='"+ Gender +"', "
            + "Class='"+txtClass.getText()+"', "
            + "Address='"+txtAddress.getText()+"', "
            + "Phone_Number='"+txtpn.getText()+"', "
            + "Favorite_Lesson='"+txtFL.getText()+"', "
            + "Favorite_Teacher='"+txtFT.getText()+"', "
            + "PSG_destination='"+txtPD.getText()+"' "
            + "WHERE NIS='"+txtNIS.getText()+"'";

            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil diupdate", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal diupdate", "Sukses", jOptionPane1.WARNING_MESSAGE);
            }
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtNIS.setText("");
        txtcname.setText("");
        txtnname.setText("");
        txtClass.setText("");
        buttonGroup1.clearSelection();
        txtAddress.setText("");
        txtFT.setText("");
        txtPD.setText("");
        txtpn.setText("");
        txtFL.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if ("".equals(txtNIS.getText()) || "".equals(txtcname.getText()) || "".equals(txtnname.getText()) || "".equals(txtClass.getText()) || "".equals(txtPD.getText()) ||  "".equals(txtpn.getText ()) ||  "".equals(txtFT.getText()) || "".equals(txtFL.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else {
            String Gender = "";
            if (rbMan.isSelected()) {
                Gender = "L";
            } else {
                Gender = "P";
            }

            String SQL = "INSERT INTO tb_content (NIS,Complete_Name,Nick_Name,Gender,Class,Address,Phone_Number,Favorite_Lesson,Favorite_Teacher,PSG_destination)" + " VALUES ('" + txtNIS.getText()
            + "','" + txtcname.getText() + "', '"
            + txtnname.getText() + "', '"
            + Gender + "','"
            + txtClass.getText()+"','"
            + txtAddress.getText()+"','"
            + txtpn.getText()+"', '"
            + txtFL.getText()+"','"
            + txtFT.getText()+"','"
            + txtPD.getText() + "')";

            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                jOptionPane1.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", jOptionPane1.WARNING_MESSAGE);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        if (baris != 1) {
            txtNIS.setText(jTable1.getValueAt(baris, 0).toString());
            txtcname.setText(jTable1.getValueAt(baris, 1).toString());
            txtnname.setText(jTable1.getValueAt(baris, 2).toString());
            if ("Man".equals(jTable1.getValueAt(baris, 3).toString())) {
                rbMan.setSelected(true);
            } else {
                rbWoman.setSelected(true);
            }
            txtClass.setText(jTable1.getValueAt(baris, 4).toString());
            txtAddress.setText(jTable1.getValueAt(baris, 5).toString());
            txtpn.setText(jTable1.getValueAt(baris, 6).toString());
            txtFL.setText(jTable1.getValueAt(baris, 7).toString());
            txtFT.setText(jTable1.getValueAt(baris, 8).toString());
            txtPD.setText(jTable1.getValueAt(baris, 9).toString());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTActionPerformed

    private void txtcnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnameActionPerformed

    private void txtFLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFLActionPerformed

    private void txtpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpnActionPerformed

    private void txtClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassActionPerformed

    private void rbWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWomanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWomanActionPerformed

    private void rbManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbManActionPerformed

    private void txtnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnnameActionPerformed

    private void txtNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNISActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jPD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbMan;
    private javax.swing.JRadioButton rbWoman;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtFL;
    private javax.swing.JTextField txtFT;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextArea txtPD;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtnname;
    private javax.swing.JTextField txtpn;
    // End of variables declaration//GEN-END:variables

    

   
}
